require: 
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'codebreaker.gemspec'
    - 'vendor/bundle/**/*'
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/MessageSpies:
  EnforcedStyle: receive