require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/bundle/**/*'
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Lint/MissingSuper:
  Exclude:
    - 'consoles/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/MessageSpies:
  EnforcedStyle: receive
